using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;

namespace Editor.DataGeneration
{
    /// <summary>
    /// Editor tool that reads a <see cref="InputActionAsset"/> and generates
    /// a <c>GameAction</c> enum containing one member per action.
    /// This eliminates hardcoded action-name strings while remaining type-safe.
    /// </summary>
    public static class GameActionGenerator
    {
        /// <summary>
        /// Relative path (from the project root) where the generated file will be written.
        /// </summary>
        private const string OUTPUT_PATH = "Assets/Scripts/Data/GameAction.cs";

        [MenuItem("Minecraft Clone/Generate Game Actions")]
        public static void Generate()
        {
            TryGenerate();
        }

        /// <summary>
        /// Generates the GameAction enum from the first InputActionAsset found in the project.
        /// Returns true on success, false on failure.
        /// </summary>
        public static bool TryGenerate()
        {
            // --- Find the InputActionAsset ---
            string[] guids = AssetDatabase.FindAssets("t:InputActionAsset");
            switch (guids.Length)
            {
                case 0:
                    Debug.LogError("[GameActionGenerator] Could not find an 'InputActionAsset' in the project.");
                    return false;
                case > 1:
                    Debug.LogWarning("[GameActionGenerator] Multiple 'InputActionAsset' assets found. Using the first one.");
                    break;
            }

            string assetPath = AssetDatabase.GUIDToAssetPath(guids[0]);
            InputActionAsset asset = AssetDatabase.LoadAssetAtPath<InputActionAsset>(assetPath);

            if (asset == null)
            {
                Debug.LogError($"[GameActionGenerator] Failed to load InputActionAsset at '{assetPath}'.");
                return false;
            }

            // --- Count total actions across all maps ---
            int totalActions = 0;
            foreach (InputActionMap map in asset.actionMaps)
            {
                totalActions += map.actions.Count;
            }

            if (totalActions == 0)
            {
                Debug.LogError("[GameActionGenerator] InputActionAsset has no actions defined.");
                return false;
            }

            // --- Generate ---
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// ==========================================================================");
            sb.AppendLine("// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY");
            sb.AppendLine("// Generated by: Minecraft Clone > Generate Game Actions");
            sb.AppendLine($"// Source asset: {assetPath}");
            sb.AppendLine($"// Action count: {totalActions}");
            sb.AppendLine("// ==========================================================================");
            sb.AppendLine();
            sb.AppendLine("// ReSharper disable UnusedMember.Global");
            sb.AppendLine();
            sb.AppendLine("namespace Data");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Type-safe enum of all actions defined in the <c>GameInputActions</c> asset.");
            sb.AppendLine("    /// Member names exactly match the action names in the asset, so");
            sb.AppendLine("    /// <c>GameAction.ToggleFlying.ToString()</c> can be passed directly to");
            sb.AppendLine("    /// <c>InputActionAsset.FindAction()</c>.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public enum GameAction");
            sb.AppendLine("    {");

            foreach (InputActionMap map in asset.actionMaps)
            {
                sb.AppendLine($"        // ── {map.name} ──");

                foreach (InputAction action in map.actions)
                {
                    string safeName = action.name;

                    // Action names in our asset are already valid C# identifiers (PascalCase, no spaces).
                    // If one ever contained spaces, strip them:
                    if (safeName.Contains(" "))
                    {
                        string original = safeName;
                        safeName = safeName.Replace(" ", "");
                        sb.AppendLine($"        /// <summary>Original name: \"{original}\"</summary>");
                    }

                    sb.AppendLine($"        {safeName},");
                }

                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // --- Write to disk ---
            string fullPath = Path.Combine(Application.dataPath, "..", OUTPUT_PATH);
            fullPath = Path.GetFullPath(fullPath); // Normalize

            // Ensure the directory exists
            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            Debug.Log($"[GameActionGenerator] Successfully generated {totalActions} game actions → {OUTPUT_PATH}");
            return true;
        }
    }

    /// <summary>
    /// Asset postprocessor that logs a warning when an <see cref="InputActionAsset"/> is reimported,
    /// reminding the developer to re-run the Game Action generator.
    /// </summary>
    public class InputActionsChangeDetector : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            foreach (string path in importedAssets)
            {
                if (path.EndsWith(".inputactions"))
                {
                    Debug.LogWarning(
                        $"[InputActionsChangeDetector] InputActions asset was modified ({path}). " +
                        "Consider running 'Minecraft Clone > Generate Game Actions' to keep GameAction.cs in sync.");
                    return; // Only warn once per import batch
                }
            }
        }
    }
}
