using System.Globalization;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Data;
using UnityEditor;
using UnityEngine;

namespace Editor
{
    /// <summary>
    /// Editor tool that reads the <see cref="BlockDatabase"/> ScriptableObject and generates
    /// a static <c>BlockIDs</c> class containing <c>public const ushort</c> fields for each
    /// block type. This eliminates hardcoded magic numbers while remaining 100% Burst-compatible.
    /// </summary>
    public static class BlockIdGenerator
    {
        /// <summary>
        /// Relative path (from the project root) where the generated file will be written.
        /// </summary>
        private const string OUTPUT_PATH = "Assets/Scripts/Data/BlockIDs.cs";

        [MenuItem("Minecraft Clone/Generate Block IDs")]
        public static void Generate()
        {
            // --- Find the BlockDatabase asset ---
            string[] guids = AssetDatabase.FindAssets("t:BlockDatabase");
            if (guids.Length == 0)
            {
                Debug.LogError("[BlockIdGenerator] Could not find a 'BlockDatabase' asset in the project.");
                return;
            }

            if (guids.Length > 1)
            {
                Debug.LogWarning("[BlockIdGenerator] Multiple 'BlockDatabase' assets found. Using the first one.");
            }

            string assetPath = AssetDatabase.GUIDToAssetPath(guids[0]);
            BlockDatabase db = AssetDatabase.LoadAssetAtPath<BlockDatabase>(assetPath);

            if (db == null)
            {
                Debug.LogError($"[BlockIdGenerator] Failed to load BlockDatabase at '{assetPath}'.");
                return;
            }

            if (db.blockTypes == null || db.blockTypes.Length == 0)
            {
                Debug.LogError("[BlockIdGenerator] BlockDatabase has no block types defined.");
                return;
            }

            // --- Validate Air invariant ---
            if (db.blockTypes[0].blockName != "Air")
            {
                Debug.LogError(
                    $"[BlockIdGenerator] CRITICAL: blockTypes[0] must be 'Air' but is '{db.blockTypes[0].blockName}'. " +
                    "Air at index 0 is a locked architectural invariant (NativeArray zero-initialization, meshing, lighting). " +
                    "Refusing to generate. Fix the BlockDatabase before running this tool.");
                return;
            }

            // --- Generate ---
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// ==========================================================================");
            sb.AppendLine("// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY");
            sb.AppendLine($"// Generated by: Minecraft Clone > Generate Block IDs");
            sb.AppendLine($"// Source asset: {assetPath}");
            sb.AppendLine($"// Block count: {db.blockTypes.Length}");
            sb.AppendLine("// ==========================================================================");
            sb.AppendLine();
            sb.AppendLine("namespace Data");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Compile-time block ID constants generated from the <see cref=\"BlockDatabase\"/> asset.");
            sb.AppendLine("    /// These are safe to use inside Burst jobs — they compile down to raw integer literals.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class BlockIDs");
            sb.AppendLine("    {");

            for (int i = 0; i < db.blockTypes.Length; i++)
            {
                string rawName = db.blockTypes[i].blockName;
                string safeName = SanitizeIdentifier(rawName);

                if (string.IsNullOrEmpty(safeName))
                {
                    Debug.LogWarning($"[BlockIdGenerator] Block at index {i} has an empty or unsanitizable name ('{rawName}'). Skipping.");
                    continue;
                }

                // Emit a comment with the original name if it differs from the sanitized version
                if (safeName != rawName)
                {
                    sb.AppendLine($"        /// <summary>Original name: \"{rawName}\"</summary>");
                }

                sb.AppendLine($"        public const ushort {safeName} = {i};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // --- Write to disk ---
            string fullPath = Path.Combine(Application.dataPath, "..", OUTPUT_PATH);
            fullPath = Path.GetFullPath(fullPath); // Normalize

            File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            Debug.Log($"[BlockIdGenerator] Successfully generated {db.blockTypes.Length} block IDs → {OUTPUT_PATH}");
        }

        /// <summary>
        /// Converts a human-readable block name into a valid C# PascalCase identifier.
        /// </summary>
        /// <param name="name">The raw block name from the database (e.g., "Oak Log", "Tall Grass").</param>
        /// <returns>A sanitized PascalCase identifier (e.g., "OakLog", "TallGrass").</returns>
        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return string.Empty;

            // Convert to title case (handles "oak log" -> "Oak Log") and remove spaces
            TextInfo textInfo = CultureInfo.InvariantCulture.TextInfo;
            string titleCase = textInfo.ToTitleCase(name.ToLowerInvariant());
            titleCase = titleCase.Replace(" ", "");

            // Remove any remaining non-alphanumeric characters (except underscores)
            titleCase = Regex.Replace(titleCase, @"[^a-zA-Z0-9_]", "");

            // Ensure it doesn't start with a digit
            if (titleCase.Length > 0 && char.IsDigit(titleCase[0]))
            {
                titleCase = "_" + titleCase;
            }

            return titleCase;
        }
    }

    /// <summary>
    /// Asset postprocessor that logs a warning when the BlockDatabase asset is reimported,
    /// reminding the developer to re-run the Block ID generator.
    /// </summary>
    public class BlockDatabaseChangeDetector : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            foreach (string path in importedAssets)
            {
                if (path.EndsWith(".asset") && AssetDatabase.LoadAssetAtPath<BlockDatabase>(path) != null)
                {
                    Debug.LogWarning(
                        $"[BlockDatabaseChangeDetector] BlockDatabase asset was modified ({path}). " +
                        "Consider running 'Minecraft Clone > Generate Block IDs' to keep BlockIDs.cs in sync.");
                    return; // Only warn once per import batch
                }
            }
        }
    }
}
