using System.Runtime.CompilerServices;
using Data;
using Unity.Burst;
using Unity.Mathematics;

namespace Jobs.BurstData
{
    /// <summary>
    /// Burst-safe rotation matrix provider for custom mesh blocks.
    /// </summary>
    /// <remarks>
    /// <para>Standard cubes use face-remap LUTs (see <see cref="BurstFacing6MeshUtility"/>,
    /// <see cref="BurstAxis3MeshUtility"/>). Custom meshes have arbitrary geometry whose
    /// <b>vertices and normals must be physically rotated</b> in 3D space. This class
    /// provides precomputed <see cref="float3x3"/> rotation matrices for every orientation
    /// in every <see cref="MetadataSchema"/>.</para>
    /// <para>All rotations are around the block center <c>(0.5, 0.5, 0.5)</c>. Caller pattern:</para>
    /// <code>
    /// float3 center = new float3(0.5f, 0.5f, 0.5f);
    /// float3 rotated = math.mul(matrix, vertPos - center) + center;
    /// </code>
    /// <para>Matrices are <b>frozen</b> — they are mathematically derived from the same
    /// conventions used by the face-remap LUTs and cross-validated against them with an
    /// automated script. Any change requires a new save version + migration step per
    /// <c>PER_BLOCK_METADATA_SCHEMAS.md §9.6</c>.</para>
    /// </remarks>
    [BurstCompile]
    public static class BurstCustomMeshRotationUtility
    {
        // =====================================================================
        //  Precomputed rotation matrix LUTs
        //  Generated by generate_rotation_matrices.py and cross-validated
        //  against BurstAxis3MeshUtility, BurstFacing6MeshUtility, and
        //  BurstFacing6Roll2MeshUtility face-remap LUTs (all 144+18+24 entries).
        // =====================================================================

        #region Axis3 (3 entries)

        /// <summary>
        /// Rotation matrices for <see cref="MetadataSchema.Axis3"/>, indexed by axis value
        /// (<c>0=Y, 1=X, 2=Z</c>).
        /// </summary>
        private static readonly float3x3[] s_axis3Matrices =
        {
            // Axis Y(0): identity
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, 1f, 0f), new float3(0f, 0f, 1f)),
            // Axis X(1): -90° Z, top→+X
            new float3x3(new float3(0f, -1f, 0f), new float3(1f, 0f, 0f), new float3(0f, 0f, 1f)),
            // Axis Z(2): +90° X, top→+Z
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, 0f, 1f), new float3(0f, -1f, 0f)),
        };

        #endregion

        #region Facing6 (6 entries)

        /// <summary>
        /// Rotation matrices for <see cref="MetadataSchema.Facing6"/>, indexed by facing value
        /// (<c>0=South, 1=North, 2=Top, 3=Bottom, 4=West, 5=East</c>).
        /// </summary>
        /// <remarks>
        /// Convention: the block's front face (+Z) rotates to face <b>toward the player</b>
        /// (opposite the named facing direction). South (0) is identity — the block's canonical
        /// front already faces +Z.
        /// </remarks>
        private static readonly float3x3[] s_facing6Matrices =
        {
            // South(0): identity, front=+Z
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, 1f, 0f), new float3(0f, 0f, 1f)),
            // North(1): 180° Y, front=-Z
            new float3x3(new float3(-1f, 0f, 0f), new float3(0f, 1f, 0f), new float3(0f, 0f, -1f)),
            // Top(2): +90° X, front=-Y
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, 0f, 1f), new float3(0f, -1f, 0f)),
            // Bottom(3): -90° X, front=+Y
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, 0f, -1f), new float3(0f, 1f, 0f)),
            // West(4): +90° Y, front=+X
            new float3x3(new float3(0f, 0f, -1f), new float3(0f, 1f, 0f), new float3(1f, 0f, 0f)),
            // East(5): -90° Y, front=-X
            new float3x3(new float3(0f, 0f, 1f), new float3(0f, 1f, 0f), new float3(-1f, 0f, 0f)),
        };

        #endregion

        #region Facing6Roll2 (24 entries)

        /// <summary>
        /// Rotation matrices for <see cref="MetadataSchema.Facing6Roll2"/>, flat-indexed by
        /// <c>facing * 4 + roll</c>. 6 facings × 4 rolls = 24 unique orientations.
        /// </summary>
        private static readonly float3x3[] s_facing6Roll2Matrices =
        {
            // Facing=South(0), Roll=0
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, 1f, 0f), new float3(0f, 0f, 1f)),
            // Facing=South(0), Roll=1
            new float3x3(new float3(0f, -1f, 0f), new float3(1f, 0f, 0f), new float3(0f, 0f, 1f)),
            // Facing=South(0), Roll=2
            new float3x3(new float3(-1f, 0f, 0f), new float3(0f, -1f, 0f), new float3(0f, 0f, 1f)),
            // Facing=South(0), Roll=3
            new float3x3(new float3(0f, 1f, 0f), new float3(-1f, 0f, 0f), new float3(0f, 0f, 1f)),
            // Facing=North(1), Roll=0
            new float3x3(new float3(-1f, 0f, 0f), new float3(0f, 1f, 0f), new float3(0f, 0f, -1f)),
            // Facing=North(1), Roll=1
            new float3x3(new float3(0f, -1f, 0f), new float3(-1f, 0f, 0f), new float3(0f, 0f, -1f)),
            // Facing=North(1), Roll=2
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, -1f, 0f), new float3(0f, 0f, -1f)),
            // Facing=North(1), Roll=3
            new float3x3(new float3(0f, 1f, 0f), new float3(1f, 0f, 0f), new float3(0f, 0f, -1f)),
            // Facing=Top(2), Roll=0
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, 0f, 1f), new float3(0f, -1f, 0f)),
            // Facing=Top(2), Roll=1
            new float3x3(new float3(0f, 0f, -1f), new float3(1f, 0f, 0f), new float3(0f, -1f, 0f)),
            // Facing=Top(2), Roll=2
            new float3x3(new float3(-1f, 0f, 0f), new float3(0f, 0f, -1f), new float3(0f, -1f, 0f)),
            // Facing=Top(2), Roll=3
            new float3x3(new float3(0f, 0f, 1f), new float3(-1f, 0f, 0f), new float3(0f, -1f, 0f)),
            // Facing=Bottom(3), Roll=0
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, 0f, -1f), new float3(0f, 1f, 0f)),
            // Facing=Bottom(3), Roll=1
            new float3x3(new float3(0f, 0f, 1f), new float3(1f, 0f, 0f), new float3(0f, 1f, 0f)),
            // Facing=Bottom(3), Roll=2
            new float3x3(new float3(-1f, 0f, 0f), new float3(0f, 0f, 1f), new float3(0f, 1f, 0f)),
            // Facing=Bottom(3), Roll=3
            new float3x3(new float3(0f, 0f, -1f), new float3(-1f, 0f, 0f), new float3(0f, 1f, 0f)),
            // Facing=West(4), Roll=0
            new float3x3(new float3(0f, 0f, -1f), new float3(0f, 1f, 0f), new float3(1f, 0f, 0f)),
            // Facing=West(4), Roll=1
            new float3x3(new float3(0f, -1f, 0f), new float3(0f, 0f, -1f), new float3(1f, 0f, 0f)),
            // Facing=West(4), Roll=2
            new float3x3(new float3(0f, 0f, 1f), new float3(0f, -1f, 0f), new float3(1f, 0f, 0f)),
            // Facing=West(4), Roll=3
            new float3x3(new float3(0f, 1f, 0f), new float3(0f, 0f, 1f), new float3(1f, 0f, 0f)),
            // Facing=East(5), Roll=0
            new float3x3(new float3(0f, 0f, 1f), new float3(0f, 1f, 0f), new float3(-1f, 0f, 0f)),
            // Facing=East(5), Roll=1
            new float3x3(new float3(0f, -1f, 0f), new float3(0f, 0f, 1f), new float3(-1f, 0f, 0f)),
            // Facing=East(5), Roll=2
            new float3x3(new float3(0f, 0f, -1f), new float3(0f, -1f, 0f), new float3(-1f, 0f, 0f)),
            // Facing=East(5), Roll=3
            new float3x3(new float3(0f, 1f, 0f), new float3(0f, 0f, -1f), new float3(-1f, 0f, 0f)),
        };

        #endregion

        #region HorizontalOnly (4 entries)

        /// <summary>
        /// Rotation matrices for <see cref="MetadataSchema.HorizontalOnly"/>, indexed by yaw value
        /// (<c>0=North, 1=South, 2=West, 3=East</c>).
        /// </summary>
        private static readonly float3x3[] s_horizontalOnlyMatrices =
        {
            // North(0): identity
            new float3x3(new float3(1f, 0f, 0f), new float3(0f, 1f, 0f), new float3(0f, 0f, 1f)),
            // South(1): 180° Y
            new float3x3(new float3(-1f, 0f, 0f), new float3(0f, 1f, 0f), new float3(0f, 0f, -1f)),
            // West(2): +90° Y
            new float3x3(new float3(0f, 0f, -1f), new float3(0f, 1f, 0f), new float3(1f, 0f, 0f)),
            // East(3): -90° Y
            new float3x3(new float3(0f, 0f, 1f), new float3(0f, 1f, 0f), new float3(-1f, 0f, 0f)),
        };

        #endregion

        // =====================================================================
        //  Public API
        // =====================================================================

        /// <summary>
        /// Returns the <see cref="float3x3"/> rotation matrix for a given schema and raw metadata byte.
        /// This is the primary entry point for custom mesh rotation — one call, schema-aware dispatch.
        /// </summary>
        /// <param name="schema">The block's metadata schema.</param>
        /// <param name="meta">The raw metadata byte from the packed voxel data.</param>
        /// <param name="defaultMeta">The block type's default metadata (used as fallback by
        /// <see cref="BurstVoxelMetadataUtility.NormalizeMeta"/>).</param>
        /// <returns>A rotation matrix to apply to custom mesh vertices and normals.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float3x3 GetRotationMatrix(MetadataSchema schema, byte meta, byte defaultMeta)
        {
            switch (schema)
            {
                case MetadataSchema.Axis3:
                {
                    byte normalized = BurstVoxelMetadataUtility.NormalizeMeta(MetadataSchema.Axis3, meta, defaultMeta);
                    return GetAxis3Matrix(BurstVoxelMetadataUtility.DecodeAxis3(normalized));
                }
                case MetadataSchema.Facing6:
                {
                    byte normalized = BurstVoxelMetadataUtility.NormalizeMeta(MetadataSchema.Facing6, meta, defaultMeta);
                    return GetFacing6Matrix(BurstVoxelMetadataUtility.DecodeFacing6(normalized));
                }
                case MetadataSchema.Facing6Roll2:
                {
                    byte normalized = BurstVoxelMetadataUtility.NormalizeMeta(MetadataSchema.Facing6Roll2, meta, defaultMeta);
                    BurstVoxelMetadataUtility.DecodeFacing6Roll2(normalized, out byte facing, out byte roll);
                    return GetFacing6Roll2Matrix(facing, roll);
                }
                case MetadataSchema.HorizontalOnly:
                {
                    byte normalized = BurstVoxelMetadataUtility.NormalizeMeta(MetadataSchema.HorizontalOnly, meta, defaultMeta);
                    return GetHorizontalOnlyMatrix(BurstVoxelMetadataUtility.DecodeHorizontalOnly(normalized));
                }
                default:
                    return float3x3.identity;
            }
        }

        /// <summary>
        /// Returns the rotation matrix for an <see cref="MetadataSchema.Axis3"/> orientation.
        /// </summary>
        /// <param name="axis">The axis value: 0=Y, 1=X, 2=Z.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float3x3 GetAxis3Matrix(byte axis)
        {
            return s_axis3Matrices[math.min(axis, 2)];
        }

        /// <summary>
        /// Returns the rotation matrix for a <see cref="MetadataSchema.Facing6"/> orientation.
        /// </summary>
        /// <param name="facing">The facing value: 0=South, 1=North, 2=Top, 3=Bottom, 4=West, 5=East.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float3x3 GetFacing6Matrix(byte facing)
        {
            return s_facing6Matrices[math.min(facing, 5)];
        }

        /// <summary>
        /// Returns the rotation matrix for a <see cref="MetadataSchema.Facing6Roll2"/> orientation.
        /// </summary>
        /// <param name="facing">The facing value: 0-5.</param>
        /// <param name="roll">The roll value: 0-3.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float3x3 GetFacing6Roll2Matrix(byte facing, byte roll)
        {
            return s_facing6Roll2Matrices[math.min(facing, 5) * 4 + math.min(roll, 3)];
        }

        /// <summary>
        /// Returns the rotation matrix for a <see cref="MetadataSchema.HorizontalOnly"/> orientation.
        /// </summary>
        /// <param name="yaw">The yaw value: 0=North, 1=South, 2=West, 3=East.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float3x3 GetHorizontalOnlyMatrix(byte yaw)
        {
            return s_horizontalOnlyMatrices[math.min(yaw, 3)];
        }

        /// <summary>
        /// Returns the Y-axis rotation matrix for a legacy rotation <b>angle</b> in degrees. The
        /// standard-cube legacy / <see cref="MetadataSchema.HorizontalOnly"/> meshing path works in
        /// angles (via <see cref="Helpers.VoxelHelper.GetRotationAngle"/>, which only ever yields
        /// 0/90/180/270), so this maps the angle onto the same frozen, cross-validated
        /// <see cref="s_horizontalOnlyMatrices"/> entries as <see cref="GetHorizontalOnlyMatrix"/> —
        /// keeping a single source of truth for the quarter-turn Y rotations. Any non-quarter angle
        /// (not expected in practice) falls back to a computed Y rotation.
        /// </summary>
        /// <param name="degrees">The Y-axis rotation in degrees.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float3x3 GetYRotationMatrix(float degrees)
        {
            float normalized = degrees % 360f;
            if (normalized < 0f) normalized += 360f;

            // Map the angle to the matching frozen yaw matrix (0=North, 1=South, 2=West, 3=East).
            // Exact float equality is intentional and correct here: 0/90/180/270 are all exactly
            // representable in IEEE-754 and `% 360f` of an exact multiple preserves that, so these are
            // a provably-correct fast path. Any non-cardinal angle deliberately falls through to the
            // computed sincos rotation below.
            // ReSharper disable CompareOfFloatsByEqualityOperator
            if (normalized == 0f) return s_horizontalOnlyMatrices[0]; // 0°
            if (normalized == 90f) return s_horizontalOnlyMatrices[2]; // 90°  -> West
            if (normalized == 180f) return s_horizontalOnlyMatrices[1]; // 180° -> South
            if (normalized == 270f) return s_horizontalOnlyMatrices[3]; // 270° -> East
            // ReSharper restore CompareOfFloatsByEqualityOperator

            math.sincos(math.radians(degrees), out float sin, out float cos);
            return new float3x3(
                cos, 0f, sin,
                0f, 1f, 0f,
                -sin, 0f, cos);
        }
    }
}
