// ==========================================================================
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by: Minecraft Clone > Generate Block IDs
// Source asset: Assets/Resources/Data/BlockDatabase.asset
// Block count: 38
// ==========================================================================

// ReSharper disable UnusedMember.Global
namespace Data
{
    /// <summary>
    /// Compile-time block ID constants generated from the <see cref="BlockDatabase"/> asset.
    /// These are safe to use inside Burst jobs — they compile down to raw integer literals.
    /// </summary>
    public static class BlockIDs
    {
        public const ushort Air = 0;
        public const ushort Stone = 1;
        public const ushort Grass = 2;
        public const ushort Dirt = 3;
        public const ushort Sand = 4;
        public const ushort Snow = 5;
        /// <summary>Original name: "Grass Snowy"</summary>
        public const ushort GrassSnowy = 6;
        /// <summary>Original name: "Stone Walkway"</summary>
        public const ushort StoneWalkway = 7;
        public const ushort Bedrock = 8;
        /// <summary>Original name: "Desert Cracked"</summary>
        public const ushort DesertCracked = 9;
        /// <summary>Original name: "Grass Rocky"</summary>
        public const ushort GrassRocky = 10;
        public const ushort Tile = 11;
        public const ushort Wood = 12;
        public const ushort Facade = 13;
        /// <summary>Original name: "Oak Log"</summary>
        public const ushort OakLog = 14;
        /// <summary>Original name: "Oak Leaves"</summary>
        public const ushort OakLeaves = 15;
        public const ushort Cactus = 16;
        /// <summary>Original name: "Stone Half Slab"</summary>
        public const ushort StoneHalfSlab = 17;
        /// <summary>Original name: "Directional Block"</summary>
        public const ushort DirectionalBlock = 18;
        public const ushort Water = 19;
        public const ushort Lava = 20;
        /// <summary>Original name: "Coal Ore"</summary>
        public const ushort CoalOre = 21;
        /// <summary>Original name: "Grass Blades"</summary>
        public const ushort GrassBlades = 22;
        /// <summary>Original name: "Debug Lamp 01"</summary>
        public const ushort DebugLamp01 = 23;
        /// <summary>Original name: "Debug Lamp 02"</summary>
        public const ushort DebugLamp02 = 24;
        /// <summary>Original name: "Debug Lamp 03"</summary>
        public const ushort DebugLamp03 = 25;
        /// <summary>Original name: "Debug Lamp 04"</summary>
        public const ushort DebugLamp04 = 26;
        /// <summary>Original name: "Debug Lamp 05"</summary>
        public const ushort DebugLamp05 = 27;
        /// <summary>Original name: "Debug Lamp 06"</summary>
        public const ushort DebugLamp06 = 28;
        /// <summary>Original name: "Debug Lamp 07"</summary>
        public const ushort DebugLamp07 = 29;
        /// <summary>Original name: "Debug Lamp 08"</summary>
        public const ushort DebugLamp08 = 30;
        /// <summary>Original name: "Debug Lamp 09"</summary>
        public const ushort DebugLamp09 = 31;
        /// <summary>Original name: "Debug Lamp 10"</summary>
        public const ushort DebugLamp10 = 32;
        /// <summary>Original name: "Debug Lamp 11"</summary>
        public const ushort DebugLamp11 = 33;
        /// <summary>Original name: "Debug Lamp 12"</summary>
        public const ushort DebugLamp12 = 34;
        /// <summary>Original name: "Debug Lamp 13"</summary>
        public const ushort DebugLamp13 = 35;
        /// <summary>Original name: "Debug Lamp 14"</summary>
        public const ushort DebugLamp14 = 36;
        /// <summary>Original name: "Debug Lamp 15"</summary>
        public const ushort DebugLamp15 = 37;
    }
}
