using UnityEngine;

namespace Data
{
    /// <summary>
    /// Stores the vertex Y-positions for each of the 16 possible fluid metadata levels.
    /// <para>
    /// The 16 entries map to the 4-bit FluidLevel field in the voxel metadata:
    /// <list type="bullet">
    ///   <item><description>Index 0: Source block height (typically 0.875, slightly below block top).</description></item>
    ///   <item><description>Indices 1-7: Horizontal flow levels with decreasing height.</description></item>
    ///   <item><description>Indices 8-15: Falling blocks — always 1.0 (full block height).
    ///     Bit 3 (value 8) is the "falling flag". Lower 3 bits carry the effective upstream level.</description></item>
    /// </list>
    /// </para>
    /// <para>Generated by the <c>FluidDataGenerator</c> editor tool (Minecraft Clone menu).</para>
    /// </summary>
    [CreateAssetMenu(fileName = "FluidMeshData", menuName = "Minecraft/Fluid Mesh Data")]
    public class FluidMeshData : ScriptableObject
    {
        // We only need to store the Y-coordinate, as X and Z are fixed (0 or 1).
        // Indices 0-7: horizontal flow heights. Indices 8-15: falling (always 1.0f).
        public float[] vertexYPositions = new float[16];
    }
}