// ==========================================================================
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by: Minecraft Clone > Generate Game Actions
// Source asset: Assets/GameInputActions.inputactions
// Action count: 31
// ==========================================================================

// ReSharper disable UnusedMember.Global

namespace Data
{
    /// <summary>
    /// Type-safe enum of all actions defined in the <c>GameInputActions</c> asset.
    /// Member names exactly match the action names in the asset, so
    /// <c>GameAction.ToggleFlying.ToString()</c> can be passed directly to
    /// <c>InputActionAsset.FindAction()</c>.
    /// </summary>
    public enum GameAction
    {
        // ── Gameplay ──
        Move,
        Look,
        Jump,
        Crouch,
        Sprint,
        Attack,
        Use,
        Scroll,
        AltModifier,
        ToggleInventory,
        Escape,
        ToggleBlockHighlight,
        ToggleDebugScreen,
        SaveWorld,
        ToggleChunkBorders,
        ToggleFlying,
        CycleVisMode,
        DebugCode,
        ToggleNoclip,
        Hotbar1,
        Hotbar2,
        Hotbar3,
        Hotbar4,
        Hotbar5,
        Hotbar6,
        Hotbar7,
        Hotbar8,
        Hotbar9,

        // ── UI ──
        Point,
        Click,
        RightClick,
    }
}
